---
version: 2
defaults: &defaults
  working_directory: ~/ami-cis-ubuntu-marketplace-build
  environment:
    BASH_ENV: local.env
    REGION: us-east-1
    ORGANIZATION: feedyard
    OS: Ubuntu 1604LTS
    BUILD_REGION: us-east-1
    BUILD_ACCOUNT: 667882779648
    INSTANCE_TYPE: t2.medium
    DEPLOY_REGIONS: us-east-1
    AWS_ACCOUNTS: "538257557236,151701496001,750464328775"
    SOURCE_VERSION: "1.0.0.2"
    KEY_PAIR: ami-build-pipelines
  docker:
    - image: quay.io/thoughtworks_aelab/di-circleci-infra-agent

jobs:

  build-ami:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: docker info
      - run:
          name: decrypt secrets
          command: invoke dec
      - run:
          name: setup aws credentials
          command: bash setup_credentials.sh $di_nonprod_terraform_user_access_key $di_nonprod_terraform_user_secret_key $REGION
      - run:
          name: packer build job
          command: |
            echo $ORGANIZATION
            packer build templates/cis_ubuntu1604_marketplace_image.json

  configuration-test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: docker info
      - run:
          name: decrypt secrets
          command: invoke dec
      - run:
          name: setup aws credentials
          command: bash setup_credentials.sh $di_nonprod_terraform_user_access_key $di_nonprod_terraform_user_secret_key $REGION
      - run:
          name: test-kitchen inspec verify
          command: invoke inspec $BUILD_ACCOUNT $BUILD_REGION $INSTANCE_TYPE $KEY_PAIR

  cve-inspection:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: docker info
      - run:
          name: decrypt secrets
          command: invoke dec
      - run:
          name: setup aws credentials
          command: bash setup_credentials.sh $di_nonprod_terraform_user_access_key $di_nonprod_terraform_user_secret_key $REGION
      - run:
          name: run AWS Inspector cve package inspection
          command: invoke awsinspector $BUILD_ACCOUNT $BUILD_REGION $INSTANCE_TYPE $KEY_PAIR

workflows:
  version: 2
  ami-cis-ubuntu-nmarketplace-build-pipeline:
    jobs:
      - build-ami
      - configuration-test:
          requires:
            - build-ami
      - cve-inspection:
          requires:
            - build-ami
