---
version: 2
defaults: &defaults
  working_directory: ~/ami-cis-ubuntu-marketplace-build
  environment:
    BASH_ENV: local.env
    REGION: "us-east-1"
    ORGANIZATION: "feedyard"
    OS: "Ubuntu Linux 16.04 LTS"
    BUILD_REGION: "us-east-1"
    BUILD_ACCOUNT: "667882779648"
    INSTANCE_TYPE: "t2.medium"
    DEPLOY_REGIONS: "us-east-1"
    AWS_ACCOUNTS: "538257557236,151701496001,750464328775"
    SOURCE_VERSION: "1.0.0.2"
    KEY_PAIR: "ami-build-pipelines"
  docker:
    - image: quay.io/thoughtworks_aelab/di-circleci-infra-agent

jobs:

  # Step 1: See packer_build_stage_one.sh for changes made
#  build-cis-release-ami:
#    <<: *defaults
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          name: confirm Docker
#          command: docker info
#      - run:
#          name: decrypt secrets
#          command: invoke dec
#      - run:
#          name: setup aws credentials
#          command: bash setup_credentials.sh $di_nonprod_terraform_user_access_key $di_nonprod_terraform_user_secret_key $REGION
#      - run:
#          name: packer build job
#          command: packer build templates/cis_ubuntu1604_marketplace_release.json

  # Step 2: See packer_build_stage_two.sh for changes made
#  build-org-release-ami:
#    <<: *defaults
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          name: confirm Docker
#          command: docker info
#      - run:
#          name: decrypt secrets
#          command: invoke dec
#      - run:
#          name: setup aws credentials
#          command: bash setup_credentials.sh $di_nonprod_terraform_user_access_key $di_nonprod_terraform_user_secret_key $REGION
#      - run:
#          name: packer build job
#          command: packer build templates/cis_ubuntu1604_organization_release.json

  inspec-tests:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: docker info
      - run:
          name: decrypt secrets
          command: invoke dec
      - run:
          name: setup aws credentials
          command: bash setup_credentials.sh $di_nonprod_terraform_user_access_key $di_nonprod_terraform_user_secret_key $REGION
      - run:
          name: test-kitchen inspec verify
          command: invoke1 inspec $BUILD_ACCOUNT $BUILD_REGION "$INSTANCE_TYPE" $KEY_PAIR "$OS"

#  cve-inspection:
#    <<: *defaults
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          name: confirm Docker
#          command: docker info
#      - run:
#          name: decrypt secrets
#          command: invoke dec
#      - run:
#          name: setup aws credentials
#          command: bash setup_credentials.sh $di_nonprod_terraform_user_access_key $di_nonprod_terraform_user_secret_key $REGION
#      - run:
#          name: run AWS Inspector cve package inspection
#          command: invoke awsinspector $BUILD_ACCOUNT $BUILD_REGION "$INSTANCE_TYPE" $KEY_PAIR "$OS"

workflows:
  version: 2
  ami-cis-ubuntu-nmarketplace-build-pipeline:
    jobs:
#      - build-cis-release-ami
#      - build-org-release-ami:
#          requires:
#            - build-cis-release-ami
      - inspec-tests
#          requires:
#            - build-org-release-ami
#      - cve-inspection:
#          requires:
#            - build-org-release-ami